import {
    ArrowUpRight,
    LayoutPanelLeft,
    Loader,
    XCircle,
    CheckCircle2,
    X,
    Menu,
    Settings,
    Star,
    Check,
    CreditCard,
    Megaphone,
    Image,
    ChevronLeft,
    ChevronRight,
    Frown,
    Lock,
    PanelLeftOpen,
    BarChart3,
    User,
    Home,
    LogOut,
    Video,
    Mic,
    MessageSquare,
    CalendarDays,
    HelpCircle,
    Volume2,
    MoreHorizontal,
    PlusCircle,
    ClipboardEdit,
    Gavel,
    Book,
    Copy,
    Bell,
    Tag,
    CircleDollarSign,
    ListOrdered,
    type LucideIcon,
  } from "lucide-react";
  
  export type Icon = LucideIcon;
  
  export const Icons = {
    listOrdered: ListOrdered,
    dashboard: LayoutPanelLeft,
    goToArrow: ArrowUpRight,
    loading: Loader,
    error: XCircle,
    success: CheckCircle2,
    close: X,
    burger: Menu,
    settings: Settings,
    star: Star,
    checkmark: Check,
    news: Megaphone,
    billing: CreditCard,
    image: Image,
    back: ChevronLeft,
    sad: Frown,
    lock: Lock,
    admin: PanelLeftOpen,
    analytics: BarChart3,
    user: User,
    home: Home,
    logOut: LogOut,
    book: Book,
    video: Video,
    microphone: Mic,
    chat: MessageSquare,
    calendar: CalendarDays,
    help: HelpCircle,
    right: ChevronRight,
    volume: Volume2,
    more: MoreHorizontal,
    plus: PlusCircle,
    edit: ClipboardEdit,
    suspend: Gavel,
    copy: Copy,
    bell: Bell,
    tag: Tag,
    checkmark2: CheckCircle2,
    coin: CircleDollarSign,
  };
  